In [1]:
import numpy as np
import pandas as pd

In [2]:
data=np.genfromtxt("train.csv",delimiter=",")
pd.DataFrame(data)

          0      1        2      3       4
0      8.58  38.38  1021.03  84.37  482.26
1     21.79  58.20  1017.21  66.74  446.94
2     16.64  48.92  1011.55  78.76  452.56
3     31.38  71.32  1009.17  60.42  433.44
4      9.20  40.03  1017.05  92.46  480.38
...     ...    ...      ...    ...     ...
7171   9.32  37.73  1022.14  79.49  477.91
7172  11.20  41.38  1021.65  61.89  476.87
7173  29.80  69.34  1009.36  64.74  437.65
7174  16.37  54.30  1017.94  63.63  459.97
7175  30.11  62.04  1010.69  47.96  444.42

[7176 rows x 5 columns]

In [3]:
x_train=data[:,0:len(data[0])-1]#features
x_train_x=x_train
c=[[1]]*len(x_train)#extra feature to take care of c
x_train=np.append(x_train,c,axis=1)
y_train=data[:,len(data[0])-1:len(data[0])]#output
#score is coeeficent of determination defined as 1-u/v
# we need to give value of y_pred in .csv format
pd.DataFrame(x_train),pd.DataFrame(y_train)

(          0      1        2      3    4
 0      8.58  38.38  1021.03  84.37  1.0
 1     21.79  58.20  1017.21  66.74  1.0
 2     16.64  48.92  1011.55  78.76  1.0
 3     31.38  71.32  1009.17  60.42  1.0
 4      9.20  40.03  1017.05  92.46  1.0
 ...     ...    ...      ...    ...  ...
 7171   9.32  37.73  1022.14  79.49  1.0
 7172  11.20  41.38  1021.65  61.89  1.0
 7173  29.80  69.34  1009.36  64.74  1.0
 7174  16.37  54.30  1017.94  63.63  1.0
 7175  30.11  62.04  1010.69  47.96  1.0

 [7176 rows x 5 columns],
            0
 0     482.26
 1     446.94
 2     452.56
 3     433.44
 4     480.38
 ...      ...
 7171  477.91
 7172  476.87
 7173  437.65
 7174  459.97
 7175  444.42

 [7176 rows x 1 columns])

In [4]:
def step_gradient(m,points,y_train,learning_rate):
    m_slope=np.zeros(len(points[0]))
    N=len(points)
    for i in range(N):
        x=points[i,:]
        y=y_train[i,:]
        for j in range(len(x)):
            m_slope[j]=m_slope[j]+((-2/N)*((y-(m*x).sum())*x[j]))
    new_m = m- learning_rate*m_slope
    return new_m

In [5]:
def gd(m,x_train,y_train,learning_rate,num_iterations):
    for i in range(num_iterations):
        m=step_gradient(m,x_train,y_train,learning_rate)
        print(i,"cost:",cost(x_train,y_train,m))
    return m

In [6]:
def cost(points,y_train,m):
    total_cost = 0
    M = len(points)
    for i in range(M):
        total_cost += (y_train[i]-(points[i,:]*m).sum())**2
    return total_cost/M

In [7]:
def score(y_true,y_pred):
    u=(y_true-y_pred).sum()
    print("u:",u,end="")
    v=(y_true-y_true.mean()).sum()
    print("v:",v)
    return 1-(u/v)

In [29]:
# now since the features are more than 1 we need to use gradient decentend,so fit will give me a array of values of m
def fit(x_train,y_train):#we need to provide x_train and y_train as input
    m=np.zeros(len(x_train[0]))
    learning_rate=0.000000935
    num_iterations=100
    final_slope=gd(m,x_train,y_train,learning_rate,num_iterations)
    print(final_slope)
    return final_slope
    
def predict(m):
    x_test=np.genfromtxt("test.csv",delimiter=',')
    print(pd.DataFrame(x_test))
    y_pred=np.zeros(len(x_test))
    c=m[len(m)-1:len(m)]
    m=m[0:len(m)-1]
    for i in range(len(x_test)):
        x=x_test[i,:]
        y_pred[i]=(m*x).sum()+c
    return y_pred

m=fit(x_train,y_train)
y_pred=predict(m)

0 cost: [181313.83540819]
1 cost: [158971.43398737]
2 cost: [139386.04370106]
3 cost: [122217.45150485]
4 cost: [107167.42638415]
5 cost: [93974.53880377]
6 cost: [82409.61943347]
7 cost: [72271.77826333]
8 cost: [63384.91495716]
9 cost: [55594.65982579]
10 cost: [48765.69228171]
11 cost: [42779.39019458]
12 cost: [37531.76931431]
13 cost: [32931.67696781]
14 cost: [28899.20865223]
15 cost: [25364.32001932]
16 cost: [22265.61013986]
17 cost: [19549.2549124]
18 cost: [17168.07208847]
19 cost: [15080.701673]
20 cost: [13250.8874627]
21 cost: [11646.84724205]
22 cost: [10240.72069663]
23 cost: [9008.08545351]
24 cost: [7927.5328419]
25 cost: [6980.29600464]
26 cost: [6149.92390034]
27 cost: [5421.99553357]
28 cost: [4783.86944867]
29 cost: [4224.46413594]
30 cost: [3734.0655355]
31 cost: [3304.15829499]
32 cost: [2927.27785003]
33 cost: [2596.88075775]
34 cost: [2307.2310311]
35 cost: [2053.30049943]
36 cost: [1830.6814645]
37 cost: [1635.51013462]
38 cost: [1464.39950703]
39 cost: [1314.3805325]
40 cost: [1182.85054019]
41 cost: [1067.52802682]
42 cost: [966.41302484]
43 cost: [877.75236117]
44 cost: [800.00920291]
45 cost: [731.83636114]
46 cost: [672.052889]
47 cost: [619.62356755]
48 cost: [573.64092306]
49 cost: [533.30946333]
50 cost: [497.93185927]
51 cost: [466.89683164]
52 cost: [439.66853258]
53 cost: [415.77723741]
54 cost: [394.8111851]
55 cost: [376.4094256]
56 cost: [360.25554977]
57 cost: [346.07219312]
58 cost: [333.6162177]
59 cost: [322.67448855]
60 cost: [313.06017142]
61 cost: [304.60948719]
62 cost: [297.17886698]
63 cost: [290.64245815]
64 cost: [284.88993816]
65 cost: [279.82459817]
66 cost: [275.36166312]
67 cost: [271.42681908]
68 cost: [267.95492241]
69 cost: [264.88886809]
70 cost: [262.17859783]
71 cost: [259.78023044]
72 cost: [257.65529962]
73 cost: [255.77008576]
74 cost: [254.09503022]
75 cost: [252.60422182]
76 cost: [251.27494679]
77 cost: [250.08729421]
78 cost: [249.02381011]
79 cost: [248.06919432]
80 cost: [247.21003466]
81 cost: [246.43457399]
82 cost: [245.73250597]
83 cost: [245.09479603]
84 cost: [244.51352444]
85 cost: [243.98174872]
86 cost: [243.49338308]
87 cost: [243.0430927]
88 cost: [242.62620101]
89 cost: [242.23860854]
90 cost: [241.87672166]
91 cost: [241.53739015]
92 cost: [241.21785253]
93 cost: [240.91568804]
94 cost: [240.62877462]
95 cost: [240.35525207]
96 cost: [240.09348969]
97 cost: [239.84205799]
98 cost: [239.59970386]
99 cost: [239.3653288]
[-1.19919036e-02 -9.17504415e-03  4.45157941e-01  4.78360000e-02
  4.32464134e-04]
          0      1        2      3
0     11.95  42.03  1017.58  90.89
1     12.07  38.25  1012.67  81.66
2     26.91  74.99  1005.64  78.98
3     20.58  39.53  1005.68  62.09
4     16.78  37.20  1011.97  68.94
...     ...    ...      ...    ...
2387  29.49  69.71  1009.34  56.35
2388  27.69  65.34  1014.31  46.59
2389  24.32  66.25  1009.09  91.89
2390  23.49  42.80  1013.96  65.31
2391  21.76  60.27  1018.96  85.06

[2392 rows x 4 columns]

In [30]:
np.savetxt('y_pred_by_gd.csv',y_pred,delimiter=',',fmt='%f')